
spring:
  application:
    name: kotlin_base

  sql:
    init:
      mode: never

app:
  r2dbc:
    write:
      url: r2dbc:h2:mem:///kotlinbase;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    read:
      url: r2dbc:h2:mem:///kotlinbase;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

logging:
  level:
    org.test.kotlin_base: DEBUG
    org.springframework: ERROR
    org.springframework.r2dbc: INFO
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.transaction: DEBUG
server:
  port: 18080
