
spring:
  application:
    name: kotlin_base
  messages:
    basename: messages/message,validations/validation,enums/enum,errors/error
    fallback-to-system-locale: false
  web:
    locale: ko_KR

  sql:
    init:
      mode: never

app:
  r2dbc:
    write:
      url: r2dbc:h2:mem:///kotlinbase;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      pool:
        initial-size: 5
        min-idle: 5
        max-size: 20
        max-idle-time: 30m
        max-acquire-time: 5s
        max-create-connection-time: 5s
        validation-query: SELECT 1
    read:
      url: r2dbc:h2:mem:///kotlinbase;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      pool:
        initial-size: 5
        min-idle: 5
        max-size: 20
        max-idle-time: 30m
        max-acquire-time: 5s
        max-create-connection-time: 5s
        validation-query: SELECT 1

logging:
  level:
    org.test.kotlin_base: DEBUG
    org.springframework: ERROR
    org.springframework.r2dbc: INFO
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.transaction: DEBUG
server:
  port: 18080
